[package]
name = "gquic"
version = "0.3.0"
edition = "2021"
description = "A minimal QUIC implementation"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["net", "rt-multi-thread", "macros"] }
bytes = "1.5"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"
