[package]
name = "gquic"
version = "0.3.0"
edition = "2021"
description = "Production-ready QUIC implementation for crypto and blockchain applications"
license = "MIT"
keywords = ["quic", "crypto", "blockchain", "networking", "protocol"]
categories = ["network-programming", "cryptography"]

[dependencies]
tokio = { version = "1.0", features = ["net", "rt-multi-thread", "macros", "time"] }
bytes = "1.5"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "crypto_example"
path = "examples/crypto_example.rs"
